### ISSUE TITLE
Add Travis CI Build

### ISSUE THREAD

**Issue by johnthagen** [PistonDevelopers/music#33]
Placeholder for completing #30 PR work.

Would help clarify questions like #31 if there was a Travis build to inspect.

**Comment by johnthagen** [comment]
@bvssvni Could you enable a Travis build (even if it fails for now) and I'll try to create a PR to make it work?  Need to have the build up first so I can debug it.

**Comment by bvssvni** [comment]
Travis build is now enabled.

**Comment by johnthagen** [comment]
- [ ] [sdl2 dependency](https://github.com/AngryLawyer/rust-sdl2/blob/master/.travis.yml)
- [ ] [sdl2_mixer dependency](https://github.com/andelf/rust-sdl2_mixer/blob/master/.travis.yml)
