### ISSUE TITLE
Error: "Feature may not be used on stable release channel"

### ISSUE THREAD

**Issue by sunnystormy** [PistonDevelopers/music#34]
I currently cannot compile "piston-music":

```
/home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/current-0.1.1/src/lib.rs:2:1: 2:29 error: #[feature] may not be used on the stable release channel [E0554]
/home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/current-0.1.1/src/lib.rs:2 #![feature(core_intrinsics)]
                                                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error
Build failed, waiting for other jobs to finish...
error: Could not compile `current`.
```

**Comment by bvssvni** [comment]
Try `cargo update`.

**Comment by sunnystormy** [comment]
You da man! That got it working. Btw, is there any 3D sound support planned in the future?

**Comment by bvssvni** [comment]
I am not working on sound currently. Don't know when this will come, but I hope there will be some library you can use.

**Comment by sunnystormy** [comment]
Ya know... I *could* try to whip something up using [openal-rs](https://github.com/jpernst/openal-rs), but I think (starting out) it'd only support .WAV files. Would that be of interest to you?

**Comment by bvssvni** [comment]
Yes! There are libraries for reading other formats in Rust, and people are working on them. If we can stream to WAV directly it might work.

**Comment by sunnystormy** [comment]
Working on it now. I'm calling it "piston-sound". I'll create a repo once I get it into a usable state.

**Comment by johnthagen** [comment]
@bvssvni Just curious as the topic of formats came up, does `music` support .mp3 files?  I wasn't able to get it to work, but maybe I just didn't do something correctly?

**Comment by bvssvni** [comment]
@johnthagen I have not managed to get it working with .mp3.

**Comment by johnthagen** [comment]
@bvssvni I think this issue is resolved and can be closed.

**Comment by bvssvni** [comment]
Thanks!
