### ISSUE TITLE
pistoncore-current has been renamed to current

### ISSUE THREAD

**Issue by Ape** [PistonDevelopers/music#5]
This package depends on pistoncore-current which was renamed to current.

```
no matching package named `pistoncore-current` found (required by `piston-music`)
location searched: https://github.com/pistondevelopers/current
```

https://github.com/PistonDevelopers/current/issues/81

**Comment by bvssvni** [comment]
Thanks. This library has been falling behind because sdl2_mixer was broken for a long time. I don't know whether it is fixed yet. There has been a discussion whether to use rust-media https://github.com/PistonDevelopers/music/issues/4

If you want to work on this library, feel free to do so.

**Comment by Ape** [comment]
Piston needs a full audio API that is backed by SDL2 or OpenAL (or something else). But creating the full thing would be a lot of work, and I don't think I am up for it personally. Also, ```music``` might not be the best name for it since it should also support playing preloaded samples in addition to streaming music.

**Comment by bvssvni** [comment]
Closed by https://github.com/PistonDevelopers/music/pull/6
