### ISSUE TITLE
Enable Appveyor CI

### ISSUE THREAD

**Issue by johnthagen** [PistonDevelopers/music#76]
@bvssvni Can you enable AppVeyor so that we can have Windows coverage?

- https://ci.appveyor.com/project/PistonDevelopers/music

We already have an `appveyor.yml`, we just need to enable the CI

**Comment by bvssvni** [comment]
Done.

**Comment by johnthagen** [comment]
When I go to: https://ci.appveyor.com/project/PistonDevelopers/music

I see "Project not found or access denied." Is the build not publicly viewable? (Then I don't think we can add a convenient badge to the README that will make it obvious when the build fails).

**Comment by bvssvni** [comment]
Added badge https://github.com/PistonDevelopers/music/pull/78

**Comment by bvssvni** [comment]
It points to `PistonDevelopers/music`. Can you see where it points to?

There are two projects listed under my account, one is my fork and the other is upstream.

**Comment by johnthagen** [comment]
The badge links to: https://ci.appveyor.com/project/bvssvni/music-l080n

```
[![Build status](https://ci.appveyor.com/api/projects/status/axt1564g44543ofi?svg=true)](https://ci.appveyor.com/project/bvssvni/music-l080n)
```

**Comment by bvssvni** [comment]
Under settings it says "PistonDevelopers/music".

Do you mean that there should be an AppVeyor account for PistonDevelopers?

**Comment by johnthagen** [comment]
I think so? At least that's how Travis CI works. I know in the past it was more involved to make Appveyor point to a "group" account, but maybe that's better now.

Maybe it's okay how it is, it just wasn't clear to me what "music-1080n" meant.

**Comment by bvssvni** [comment]
Closing for now.
